/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 175
#define YY_END_OF_BUFFER 176
static yyconst short int yy_acclist[388] =
    {   0,
      170,  170,  176,  174,  175,  169,  174,  175,  168,  175,
        1,  174,  175,    4,  174,  175,  174,  175,  127,  174,
      175,  109,  174,  175,    3,  174,  175,  109,  174,  175,
      109,  174,  175,  164,  174,  175,  164,  174,  175,  164,
      174,  175,  109,  174,  175,  109,  174,  175,  109,  174,
      175,  166,  174,  175,  166,  174,  175,  166,  174,  175,
      166,  174,  175,  166,  174,  175,  166,  174,  175,  166,
      174,  175,  166,  174,  175,  166,  174,  175,  166,  174,
      175,  166,  169,  174,  175,  166,  174,  175,  166,  174,
      175,  166,  174,  175,  166,  174,  175,  166,  174,  175,

      166,  174,  175,  166,  174,  175,  166,  174,  175,  166,
      174,  175,  166,  174,  175,  166,  174,  175,  170,  175,
      173,  175,  171,  175,  172,  175,    4,  167,  160,    3,
      114,  164,  164,  164,  121,  125,  122,  124,  126,  123,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,   15,  166,  166,  166,  166,  166,  166,  166,
      166,   69,  166,  166,  166,  166,  166,  166,  166,  166,
       20,  166,   21,  166,  166,  116,  166,  166,  166,   71,

      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  142,  166,  166,   31,  166,  166,  166,  166,  166,
      166,  166,  166,  170,  164,  163,  161,  162,  161,  162,
      163,  161,  162,   57,   58,   97,  115,   83,   59,   60,
      144,    5,    7,   33,   34,  155,   61,   64,    8,  159,
       10,  111,   11,  119,  106,  107,   55,   65,   66,  165,
       12,   98,   36,  146,  156,  120,   68,  157,   89,   17,
      105,   70,  153,  112,  113,  110,   19,  117,  148,   49,
      103,   37,    2,   78,   27,   74,   72,   76,  101,  100,

       75,   44,   99,   79,  141,  166,   81,  158,  104,   82,
      118,  154,   41,  145,   32,   85,  143,   63,   62,    9,
      108,   35,   51,  165,  165,   67,   14,  147,   88,   18,
      149,  102,   22,   24,    2,   93,   73,   28,   29,   90,
       80,   30,  140,   53,   84,    6,   54,   13,   92,   16,
       91,  152,   86,   48,   23,   56,   77,  139,   43,   46,
      132,  131,  129,  130,  128,   96,   38,  151,  135,   40,
       39,   52,   26,   87,  136,   45,  150,  134,  133,   50,
      138,   25,  137,   94,   47,   42,   95
    } ;

static yyconst short int yy_accept[431] =
    {   0,
        1,    1,    1,    2,    3,    4,    6,    9,   11,   14,
       17,   19,   22,   25,   28,   31,   34,   37,   40,   43,
       46,   49,   52,   55,   58,   61,   64,   67,   70,   73,
       76,   79,   82,   86,   89,   92,   95,   98,  101,  104,
      107,  110,  113,  116,  119,  121,  123,  125,  127,  128,
      128,  129,  130,  131,  132,  133,  133,  134,  135,  135,
      135,  135,  135,  136,  137,  138,  139,  140,  141,  142,
      143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  155,  156,  157,  158,  159,  160,  161,  162,
      163,  164,  165,  166,  167,  168,  169,  170,  171,  172,

      173,  175,  176,  177,  178,  179,  180,  181,  182,  184,
      185,  186,  187,  188,  189,  190,  191,  193,  195,  196,
      198,  199,  200,  202,  203,  204,  205,  206,  207,  208,
      209,  210,  211,  212,  213,  214,  215,  216,  217,  218,
      219,  220,  221,  222,  224,  225,  227,  228,  229,  230,
      231,  232,  233,  234,  235,  235,  236,  237,  238,  239,
      242,  244,  245,  246,  247,  248,  249,  250,  251,  251,
      252,  253,  253,  253,  253,  253,  253,  253,  254,  255,
      256,  257,  258,  259,  259,  260,  261,  262,  262,  263,
      264,  265,  266,  267,  268,  268,  268,  269,  270,  271,

      272,  272,  273,  274,  274,  274,  274,  275,  276,  277,
      277,  277,  277,  277,  278,  279,  279,  279,  279,  279,
      280,  281,  282,  283,  284,  285,  285,  286,  287,  288,
      288,  289,  290,  290,  290,  290,  290,  291,  292,  292,
      293,  293,  293,  293,  294,  294,  294,  294,  294,  295,
      295,  296,  296,  297,  298,  299,  300,  301,  302,  302,
      302,  302,  302,  303,  304,  305,  305,  307,  307,  308,
      308,  309,  309,  309,  309,  310,  311,  311,  312,  313,
      313,  314,  315,  316,  316,  317,  317,  318,  319,  319,
      320,  321,  321,  321,  321,  321,  322,  322,  323,  324,

      325,  326,  327,  327,  328,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  330,  331,  332,  332,  332,  333,
      334,  334,  334,  334,  335,  336,  336,  336,  336,  336,
      336,  336,  337,  338,  338,  339,  340,  341,  341,  341,
      341,  342,  343,  344,  345,  345,  345,  345,  345,  346,
      346,  347,  347,  347,  347,  347,  347,  347,  348,  349,
      350,  350,  351,  352,  353,  353,  353,  354,  354,  355,
      356,  357,  357,  357,  357,  357,  357,  357,  358,  358,
      358,  358,  358,  359,  360,  360,  360,  361,  361,  362,
      362,  363,  364,  365,  366,  366,  367,  368,  369,  370,

      371,  372,  372,  372,  372,  373,  374,  375,  376,  376,
      376,  377,  378,  379,  379,  380,  381,  381,  382,  383,
      384,  385,  385,  386,  386,  386,  387,  387,  388,  388
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   16,   15,   17,   13,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   13,   23,
       24,   25,    1,   26,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       13,    1,   13,   27,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,    1,   55,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    3,    3,    3,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        5,    4,    1,    1,    1,    6,    7,    8,    9,    9,
        9,    9,    9,    9,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[441] =
    {   0,
        0,    0,   53,   54,  721, 1060, 1060, 1060, 1060,    0,
       55, 1060,    0,    0, 1060,  701,   45,   62,   67,   35,
       48,   44,   93,  112,   98,  109,   60,   87,  124,  135,
      136,  142,  161,   94,  164,  174,  190,  192,  217,  231,
      249,  173,  195,  218,    0, 1060, 1060, 1060,    0,   87,
     1060,    0,    0, 1060,  270,  279,  286,  291,   91,    0,
      162,  167, 1060, 1060, 1060, 1060, 1060, 1060, 1060,  203,
      307,  312,  317,  323,  329,  334,  339,  356,  364,  369,
      374,  415,  379,  384,  396,  404,  409,  427,  432,  441,
      457,  463,  470,  475,  480,  496,  502,  508,  522,  527,

      532,  537,  576,  543,  551,  558,  569,  583,  589,  596,
      604,  626,  631,  636,  641,  651,  656,  661,  666,  671,
      676,  684,  692,  697,  702,  710,  718,  755,  724,  737,
      742,  762,  770,  777,  784,  800,  806,  812,  819,  824,
      832,  838,  851,  861,  867,  877,  882,  887,  898,  904,
      909,  923,  928,    0,  332,  409,   93,    0,  238,    0,
      107, 1060, 1060, 1060, 1060,  676, 1060, 1060,  676,  695,
     1060,  657,  654,  686,  662,  674,  643, 1060, 1060, 1060,
      623,  619, 1060,  625,  309, 1060, 1060,  609, 1060, 1060,
     1060, 1060, 1060,   87,  617,  595, 1060, 1060,  934, 1060,

      607, 1060, 1060,  110,  584,  587,  620, 1060, 1060,  595,
      594,  573,  573, 1060, 1060,  586,  569,  569,  561, 1060,
     1060, 1060, 1060, 1060, 1060,  598, 1060, 1060, 1060,  553,
     1060,  591,  559,  543,  549,  550, 1060, 1060,  538, 1060,
      529,  540,  539,    0,  537,  151,  516,  527, 1060,  520,
     1060,  549, 1060,  518, 1060,  517, 1060, 1060,  500,  495,
       82,  487,  479, 1060,  488,  481, 1060,  488, 1060,  476,
     1060,  470,  468,  467, 1060, 1060,  461, 1060, 1060,  461,
     1060, 1060, 1060,  460, 1060,  448, 1060, 1060,  460, 1060,
     1060,  462,  445,   86,  439, 1060,  429, 1060, 1060, 1060,

      948, 1060,  440, 1060, 1060,  408,  406,  408,  409,  413,
      404,  412,  435, 1060, 1060, 1060,  396,  401, 1060, 1060,
      374,  383,  365, 1060,    0,  378,  358,  359,  353,  348,
      363, 1060, 1060,  358, 1060, 1060, 1060,  339,  321,  335,
     1060, 1060,  235, 1060,  325,  328,  323,  320, 1060,  303,
     1060,  288,  290,  280,  279,  255,  248, 1060, 1060, 1060,
      284,  279, 1060, 1060,  253,  274, 1060,  240, 1060,  268,
     1060,  234,  224,  223,  230,  211,  240, 1060,  233,  205,
      191,  190, 1060, 1060,  198,  219, 1060,  175, 1060,  148,
     1060, 1060, 1060, 1060,  142, 1060, 1060, 1060, 1060, 1060,

     1060,  126,  146,  115, 1060, 1060, 1060, 1060,  132,  255,
     1060, 1060, 1060,   88, 1060, 1060,   61, 1060, 1060, 1060,
     1060,   35, 1060,   41,   37, 1060,   52, 1060, 1060,  974,
      983,  992,  997, 1006, 1013, 1022, 1027, 1034, 1041, 1050
    } ;

static yyconst short int yy_def[441] =
    {   0,
      429,    1,  430,  430,  429,  429,  429,  429,  429,  431,
      432,  429,  433,  434,  429,  429,  429,  429,  429,  429,
      429,  429,  435,  435,  435,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   32,   25,   25,   25,   25,
       25,   25,   25,   25,  436,  429,  429,  429,  431,  432,
      429,  433,  434,  429,  429,  429,  429,  429,  429,  437,
      429,  437,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  438,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  436,  429,  429,  429,  437,  429,   62,
       62,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  439,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  440,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  440,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,    0,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429
    } ;

static yyconst short int yy_nxt[1116] =
    {   0,
        6,    7,    8,    9,    7,   10,   11,   12,    6,    6,
       13,   14,   15,   16,   15,   15,   17,   18,   19,   19,
       19,   15,   20,   21,   22,   23,   15,    6,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   23,   23,   33,
       34,   35,   36,   37,   23,   38,   39,   40,   41,   42,
       23,   43,   23,   44,    6,   46,   46,   51,   63,   64,
      428,   51,   55,   55,   55,   55,   67,   68,   47,   47,
       65,  427,   66,  426,   48,   48,  425,   56,   57,   58,
       58,   58,   58,   57,   58,   58,   58,   58,   86,   51,
      337,   59,   87,   51,   56,  296,   88,   60,   69,   56,

       69,   69,   69,   69,   61,   69,   69,   69,  157,  157,
      157,  157,   70,   60,  424,   70,   62,   69,  338,   69,
       69,   69,  111,   70,  161,  161,   77,  355,   89,  297,
      112,   90,   91,  356,   78,  423,  113,   80,   92,   70,
      420,   71,   72,   73,   81,   70,   70,  419,   82,   83,
       79,   84,   70,   74,  418,   85,  205,  206,   75,   76,
       93,   70,  417,   70,   70,   94,   95,   97,   99,   96,
       70,   70,   70,  100,  416,  101,   70,   98,   70,  159,
      159,  159,  102,  103,  160,  160,  161,   70,   70,  104,
      105,  106,   70,  107,   70,  415,  114,  108,  327,  328,

       70,  151,  109,  110,  116,   70,  115,  117,   69,   70,
       69,   69,   69,   70,   70,  118,   70,  119,  121,  120,
      127,  414,  122,   70,  128,   70,  123,  413,  129,  412,
      411,   70,  124,  130,  131,  125,  410,  152,  126,  409,
      132,  408,   70,  383,   70,   70,   70,   70,  407,  133,
      153,  134,  406,  135,   70,  159,  159,  159,  136,  142,
      137,  138,  405,  421,  139,  140,  143,  144,  404,  141,
       70,  403,  145,  146,  402,  401,  147,   70,  148,  149,
      384,  400,  399,   70,  398,   70,  397,   55,   55,   55,
       55,  422,  396,  155,  395,  150,  156,  156,  156,  156,

      394,   70,   56,   55,   55,   55,   55,   57,   58,   58,
       58,   58,   69,  393,   69,   69,   69,   69,   56,   69,
       69,   69,   69,   56,   69,   69,   69,  392,   69,  391,
       69,   69,   69,  390,   69,  389,   69,   69,   69,   69,
      292,   69,   69,   69,   69,  293,   69,   69,   69,  156,
      156,  156,  156,  162,  165,  294,  388,  387,  163,  166,
      386,   69,  164,   69,   69,   69,  385,  382,  381,   69,
      167,   69,   69,   69,   69,  168,   69,   69,   69,   69,
      380,   69,   69,   69,   69,  169,   69,   69,   69,   69,
      379,   69,   69,   69,  378,  377,  171,  170,  376,  375,

      374,   69,  173,   69,   69,   69,  373,  372,  172,   69,
      180,   69,   69,   69,   69,  371,   69,   69,   69,  174,
       69,  370,   69,   69,   69,  181,  156,  156,  156,  156,
      182,  183,   69,  369,   69,   69,   69,   69,  368,   69,
       69,   69,  185,  367,  366,  365,   69,  175,   69,   69,
       69,  184,  364,  176,  363,  362,  186,  177,  361,  360,
      178,  179,   69,  190,   69,   69,   69,  187,   69,  359,
       69,   69,   69,  188,  358,   69,  189,   69,   69,   69,
       69,  357,   69,   69,   69,   69,  354,   69,   69,   69,
      191,  353,  352,  351,  350,  195,  192,  349,  193,  196,

      348,   69,  194,   69,   69,   69,  197,   69,  347,   69,
       69,   69,  204,   69,  346,   69,   69,   69,  345,  344,
      343,  198,  342,  341,  201,  200,  340,   69,  202,   69,
       69,   69,   69,  339,   69,   69,   69,   69,  336,   69,
       69,   69,   69,  335,   69,   69,   69,  334,   69,  203,
       69,   69,   69,  333,  205,  206,   69,  332,   69,   69,
       69,  331,  330,   69,  329,   69,   69,   69,  208,  326,
      324,  323,  216,  207,   69,  322,   69,   69,   69,  321,
      209,   69,  320,   69,   69,   69,  218,  319,   69,  318,
       69,   69,   69,  217,   69,  317,   69,   69,   69,  316,

      315,   69,  219,   69,   69,   69,  314,  210,  313,   69,
      220,   69,   69,   69,  211,  312,  221,  311,  310,  212,
      309,  308,  213,  214,  222,  215,  307,  306,  305,  304,
      223,   69,  303,   69,   69,   69,   69,  302,   69,   69,
       69,   69,  299,   69,   69,   69,   69,  298,   69,   69,
       69,  224,  295,  291,  290,  225,   69,  226,   69,   69,
       69,   69,  228,   69,   69,   69,   69,  227,   69,   69,
       69,   69,  289,   69,   69,   69,   69,  288,   69,   69,
       69,   69,  287,   69,   69,   69,  229,  230,  231,   69,
      286,   69,   69,   69,  285,  284,  283,   69,  232,   69,

       69,   69,   69,  282,   69,   69,   69,   69,  281,   69,
       69,   69,  280,  233,   54,   69,  235,   69,   69,   69,
      429,  429,  429,   69,  234,   69,   69,   69,  429,   69,
      429,   69,   69,   69,  429,  236,  429,  429,  239,  429,
      237,  429,   69,  238,   69,   69,   69,   69,  429,   69,
       69,   69,  429,  429,  241,  429,  429,  240,  248,  242,
       69,  429,   69,   69,   69,  429,  429,   69,  249,   69,
       69,   69,  429,  429,  429,   69,  429,   69,   69,   69,
      429,  429,   69,  243,   69,   69,   69,  429,  429,   69,
      250,   69,   69,   69,  429,  244,  429,  429,  245,  429,

      429,  246,  247,  251,  252,   69,  429,   69,   69,   69,
      429,   69,  429,   69,   69,   69,  429,   69,  253,   69,
       69,   69,  429,  429,   69,  254,   69,   69,   69,   69,
      429,   69,   69,   69,  256,  255,  257,   69,  429,   69,
       69,   69,  429,   69,  429,   69,   69,   69,  429,  429,
      429,  259,  429,  262,  429,  429,   69,  258,   69,   69,
       69,  260,  429,  429,  261,  429,   69,  264,   69,  267,
       69,  429,   69,  429,   69,   69,   69,  429,  263,  265,
      429,  429,   69,  266,   69,   69,   69,   69,  429,   69,
       69,   69,   69,  429,   69,   69,   69,  429,  429,  429,

      429,  268,  269,   69,  429,   69,   69,   69,  429,   69,
      270,   69,   69,   69,   69,  429,   69,   69,   69,  429,
      429,  429,  429,  271,  429,  429,  273,  429,   69,  272,
       69,   69,   69,   69,  429,   69,   69,   69,  429,  300,
      274,  300,  300,  300,  429,  429,  429,  429,  276,  275,
      429,  429,  429,  300,  277,  300,  300,  300,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  278,  429,
      429,  429,  429,  279,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   49,  429,   49,   49,   49,   49,   49,
       49,   49,   50,   50,   50,   50,   50,   50,  429,   50,

       50,   52,  429,  429,  429,   52,   53,  429,   53,   53,
       53,   53,   53,   53,   53,   70,  429,   70,  429,  429,
       70,   70,  154,  429,  154,  429,  154,  154,  154,  154,
      154,  158,  429,  429,  429,  158,  199,  429,  429,  199,
      429,  429,  199,  301,  429,  301,  429,  429,  301,  301,
      325,  429,  325,  325,  325,  325,  325,  325,  325,    5,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429
    } ;

static yyconst short int yy_chk[1116] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,   11,   20,   20,
      427,   11,   17,   17,   17,   17,   22,   22,    3,    4,
       21,  425,   21,  424,    3,    4,  422,   17,   18,   18,
       18,   18,   18,   19,   19,   19,   19,   19,   27,   50,
      261,   18,   27,   50,   18,  194,   27,   18,   23,   19,

       23,   23,   23,   25,   18,   25,   25,   25,   59,   59,
      157,  157,   27,   18,  417,   28,   18,   24,  261,   24,
       24,   24,   34,   28,  161,  161,   25,  294,   28,  194,
       34,   28,   28,  294,   25,  414,   34,   26,   28,   28,
      409,   24,   24,   24,   26,   26,   34,  404,   26,   26,
       25,   26,   29,   24,  403,   26,  204,  204,   24,   24,
       29,   26,  402,   30,   31,   29,   29,   30,   31,   29,
       32,   30,   31,   32,  395,   32,   29,   30,   32,   61,
       61,   61,   32,   32,   62,   62,   62,   30,   31,   33,
       33,   33,   35,   33,   32,  390,   35,   33,  246,  246,

       35,   42,   33,   33,   36,   36,   35,   36,   70,   42,
       70,   70,   70,   33,   36,   36,   35,   36,   37,   36,
       38,  388,   37,   43,   38,   42,   37,  386,   38,  385,
      382,   43,   37,   38,   38,   37,  381,   43,   37,  380,
       38,  379,   37,  343,   38,   39,   44,   43,  377,   39,
       44,   39,  376,   39,   44,  159,  159,  159,   39,   40,
       39,   39,  375,  410,   39,   39,   40,   40,  374,   39,
       44,  373,   40,   40,  372,  370,   40,   41,   41,   41,
      343,  368,  366,   40,  365,   41,  362,   55,   55,   55,
       55,  410,  361,   56,  357,   41,   56,   56,   56,   56,

      356,   41,   55,   57,   57,   57,   57,   58,   58,   58,
       58,   58,   71,  355,   71,   71,   71,   72,   57,   72,
       72,   72,   73,   58,   73,   73,   73,  354,   74,  353,
       74,   74,   74,  352,   75,  350,   75,   75,   75,   76,
      185,   76,   76,   76,   77,  185,   77,   77,   77,  155,
      155,  155,  155,   71,   74,  185,  348,  347,   72,   75,
      346,   78,   73,   78,   78,   78,  345,  340,  339,   79,
       75,   79,   79,   79,   80,   76,   80,   80,   80,   81,
      338,   81,   81,   81,   83,   77,   83,   83,   83,   84,
      334,   84,   84,   84,  331,  330,   79,   78,  329,  328,

      327,   85,   81,   85,   85,   85,  326,  323,   80,   86,
       83,   86,   86,   86,   87,  322,   87,   87,   87,   81,
       82,  321,   82,   82,   82,   84,  156,  156,  156,  156,
       84,   85,   88,  318,   88,   88,   88,   89,  317,   89,
       89,   89,   87,  313,  312,  311,   90,   82,   90,   90,
       90,   86,  310,   82,  309,  308,   87,   82,  307,  306,
       82,   82,   91,   89,   91,   91,   91,   88,   92,  303,
       92,   92,   92,   88,  297,   93,   88,   93,   93,   93,
       94,  295,   94,   94,   94,   95,  293,   95,   95,   95,
       90,  292,  289,  286,  284,   92,   91,  280,   91,   92,

      277,   96,   91,   96,   96,   96,   92,   97,  274,   97,
       97,   97,   98,   98,  273,   98,   98,   98,  272,  270,
      268,   93,  266,  265,   96,   95,  263,   99,   96,   99,
       99,   99,  100,  262,  100,  100,  100,  101,  260,  101,
      101,  101,  102,  259,  102,  102,  102,  256,  104,   97,
      104,  104,  104,  254,   98,   98,  105,  252,  105,  105,
      105,  250,  248,  106,  247,  106,  106,  106,  100,  245,
      243,  242,  104,   99,  107,  241,  107,  107,  107,  239,
      102,  103,  236,  103,  103,  103,  106,  235,  108,  234,
      108,  108,  108,  105,  109,  233,  109,  109,  109,  232,

      230,  110,  107,  110,  110,  110,  226,  103,  219,  111,
      107,  111,  111,  111,  103,  218,  107,  217,  216,  103,
      213,  212,  103,  103,  108,  103,  211,  210,  207,  206,
      110,  112,  205,  112,  112,  112,  113,  201,  113,  113,
      113,  114,  196,  114,  114,  114,  115,  195,  115,  115,
      115,  111,  188,  184,  182,  111,  116,  112,  116,  116,
      116,  117,  113,  117,  117,  117,  118,  112,  118,  118,
      118,  119,  181,  119,  119,  119,  120,  177,  120,  120,
      120,  121,  176,  121,  121,  121,  114,  114,  115,  122,
      175,  122,  122,  122,  174,  173,  172,  123,  116,  123,

      123,  123,  124,  170,  124,  124,  124,  125,  169,  125,
      125,  125,  166,  119,   16,  126,  122,  126,  126,  126,
        5,    0,    0,  127,  121,  127,  127,  127,    0,  129,
        0,  129,  129,  129,    0,  124,    0,    0,  125,    0,
      124,    0,  130,  124,  130,  130,  130,  131,    0,  131,
      131,  131,    0,    0,  127,    0,    0,  126,  129,  127,
      128,    0,  128,  128,  128,    0,    0,  132,  130,  132,
      132,  132,    0,    0,    0,  133,    0,  133,  133,  133,
        0,    0,  134,  128,  134,  134,  134,    0,    0,  135,
      131,  135,  135,  135,    0,  128,    0,    0,  128,    0,

        0,  128,  128,  132,  133,  136,    0,  136,  136,  136,
        0,  137,    0,  137,  137,  137,    0,  138,  134,  138,
      138,  138,    0,    0,  139,  135,  139,  139,  139,  140,
        0,  140,  140,  140,  137,  136,  137,  141,    0,  141,
      141,  141,    0,  142,    0,  142,  142,  142,    0,    0,
        0,  139,    0,  140,    0,    0,  143,  138,  143,  143,
      143,  139,    0,    0,  139,    0,  144,  142,  144,  144,
      144,    0,  145,    0,  145,  145,  145,    0,  141,  142,
        0,    0,  146,  143,  146,  146,  146,  147,    0,  147,
      147,  147,  148,    0,  148,  148,  148,    0,    0,    0,

        0,  144,  145,  149,    0,  149,  149,  149,    0,  150,
      147,  150,  150,  150,  151,    0,  151,  151,  151,    0,
        0,    0,    0,  147,    0,    0,  149,    0,  152,  148,
      152,  152,  152,  153,    0,  153,  153,  153,    0,  199,
      150,  199,  199,  199,    0,    0,    0,    0,  151,  150,
        0,    0,    0,  301,  151,  301,  301,  301,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  152,    0,
        0,    0,    0,  153,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  431,    0,  431,  431,  431,  431,  431,
      431,  431,  432,  432,  432,  432,  432,  432,    0,  432,

      432,  433,    0,    0,    0,  433,  434,    0,  434,  434,
      434,  434,  434,  434,  434,  435,    0,  435,    0,    0,
      435,  435,  436,    0,  436,    0,  436,  436,  436,  436,
      436,  437,    0,    0,    0,  437,  438,    0,    0,  438,
        0,    0,  438,  439,    0,  439,    0,    0,  439,  439,
      440,    0,  440,  440,  440,  440,  440,  440,  440,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\scan.l"
#define INITIAL 0
#line 2 ".\\scan.l"
/* Lexical analyser for RetroBASIC
   Copyright (C) 2020 Maury Markowitz

   Based on gnbasic
   Copyright (C) 1998 James Bowman
 
This file is part of RetroBASIC.

RetroBASIC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

RetroBASIC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with RetroBASIC; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330,
Boston, MA 02111-1307, USA.  */
  
/**
 * @file scan.l
 * @author Maury Markowitz
 * @brief lex/flex scanner
 *
 */

#include "retrobasic.h"
#include "strng.h"
#include "parse.h"

//%option nodefault
#define DATA_STATEMENT 1

#line 846 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 45 ".\\scan.l"


 /* end of file */
#line 1001 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 430 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1060 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 48 ".\\scan.l"
{
          yyterminate();
        }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DATA_STATEMENT):
#line 51 ".\\scan.l"
{
          yyterminate();
        }
	YY_BREAK
/* statements */
/* REM statements are odd because they consist of a token and a line of text, but
    the rest of the line is part of the statement. If you want to keep the REM part as
    a separate token, this is the simplest solution. See:
    https://stackoverflow.com/questions/59117309/rest-of-line-in-bison/59122569#59122569
  */
case 2:
YY_RULE_SETUP
#line 61 ".\\scan.l"
{ yylval.s = str_new(str_copy(yytext + 3, yyleng - 3)); return REM; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 ".\\scan.l"
{ yylval.s = str_new(str_copy(yytext + 1, yyleng - 1)); return QUOTEREM; } // short form in MS
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 ".\\scan.l"
{ yylval.s = str_new(str_copy(yytext + 1, yyleng - 1)); return BANGREM; }  // later MS allow bang as well
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 ".\\scan.l"
{ return BYE; }   // also SYSTEM and GOODBYE
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 ".\\scan.l"
{ return CLEAR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 ".\\scan.l"
{ return CLEAR; } // synonyms
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 ".\\scan.l"
{ return DEF; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 ".\\scan.l"
{ BEGIN(DATA_STATEMENT); return DATA; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 ".\\scan.l"
{ return DIM; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 ".\\scan.l"
{ return END; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 ".\\scan.l"
{ return FOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 72 ".\\scan.l"
{ return GOSUB; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 73 ".\\scan.l"
{ return GOTO; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 ".\\scan.l"
{ return IF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 ".\\scan.l"
{ return INPUT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 ".\\scan.l"
{ return LET; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 ".\\scan.l"
{ return NEXT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 ".\\scan.l"
{ return NEW; }   // also CLEAR (sometimes with options), ERASE and SCRATCH
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 ".\\scan.l"
{ return OF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 ".\\scan.l"
{ return ON; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 81 ".\\scan.l"
{ return POKE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 ".\\scan.l"
{ return PRINT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 ".\\scan.l"
{ return READ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 ".\\scan.l"
{ return RESTORE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 ".\\scan.l"
{ return RETURN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 ".\\scan.l"
{ return RUN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 ".\\scan.l"
{ return STEP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 ".\\scan.l"
{ return STOP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 ".\\scan.l"
{ return THEN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 ".\\scan.l"
{ return TO; }
	YY_BREAK
/* extended statements found in some versions*/
case 32:
YY_RULE_SETUP
#line 93 ".\\scan.l"
{ return CALL; }    // used to call system functions in TI-99 and some other BASICs
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 94 ".\\scan.l"
{ return CLS; }     // clear screen, do not confuse with CLR or CLEAR
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 95 ".\\scan.l"
{ return CMD; }     // redirects output of PRINT to another device
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 96 ".\\scan.l"
{ return CALL; }    //
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 ".\\scan.l"
{ return GET; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 ".\\scan.l"
{ return PUT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 ".\\scan.l"
{ return INPUT_FILE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 ".\\scan.l"
{ return PRINT_FILE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 ".\\scan.l"
{ return OPTION; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 ".\\scan.l"
{ return BASE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 103 ".\\scan.l"
{ return RANDOMIZE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 ".\\scan.l"
{ return RANDOMIZE; } // this returns the RANDOMIZE token instead of making a new one
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 ".\\scan.l"
{ return SYS; }     // same as CALL
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 ".\\scan.l"
{ return SYS; }     // same as CALL
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 ".\\scan.l"
{ return USING; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 108 ".\\scan.l"
{ return VARLIST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 ".\\scan.l"
{ return PAUSE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 ".\\scan.l"
{ return POP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 ".\\scan.l"
{ return POP; }     // same as POP
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 ".\\scan.l"
{ return EXIT; }    // slightly different than pop
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 ".\\scan.l"
{ return RESUME; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 ".\\scan.l"
{ return TRAP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 ".\\scan.l"
{ return ERROR; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 ".\\scan.l"
{ return ERROR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 ".\\scan.l"
{ return RAISE; }
	YY_BREAK
/* math functions */
case 57:
YY_RULE_SETUP
#line 120 ".\\scan.l"
{ return ABS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 121 ".\\scan.l"
{ return ACS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 122 ".\\scan.l"
{ return ASN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 ".\\scan.l"
{ return ATN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 ".\\scan.l"
{ return COS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 ".\\scan.l"
{ return COSH; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 ".\\scan.l"
{ return CLOG; } // CLG on Honeywell Series 60
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 ".\\scan.l"
{ return COSH; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 128 ".\\scan.l"
{ return EXP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 129 ".\\scan.l"
{ return FIX; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 130 ".\\scan.l"
{ return FRAC; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 131 ".\\scan.l"
{ return INT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 132 ".\\scan.l"
{ return LOG; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 133 ".\\scan.l"
{ return LOG; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 134 ".\\scan.l"
{ return PI; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 135 ".\\scan.l"
{ return SIN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 136 ".\\scan.l"
{ return SINH; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 137 ".\\scan.l"
{ return SGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 138 ".\\scan.l"
{ return SQR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 139 ".\\scan.l"
{ return SINH; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 140 ".\\scan.l"
{ return ROUND; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 141 ".\\scan.l"
{ return RND; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 142 ".\\scan.l"
{ return TAN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 143 ".\\scan.l"
{ return TANH; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 144 ".\\scan.l"
{ return TANH; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 145 ".\\scan.l"
{ return VAL; }
	YY_BREAK
/* string-related functions */
case 83:
YY_RULE_SETUP
#line 148 ".\\scan.l"
{ return ASC; } // CODE on Sinclair due to being non-ASCII, CH on Atom (no parens)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 149 ".\\scan.l"
{ return ASC; } // DEC version of ASC
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 150 ".\\scan.l"
{ return CHR; } // CHR (SOL and SWTP), CHAR (MAX-BASIC), CHAR$ (Micropolis)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 151 ".\\scan.l"
{ return LEFT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 152 ".\\scan.l"
{ return RIGHT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 153 ".\\scan.l"
{ return MID; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 154 ".\\scan.l"
{ return LEN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 155 ".\\scan.l"
{ return STR; } // also NUM$ in some dialects
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 156 ".\\scan.l"
{ return INSTR; } // also INDEX and POS
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 157 ".\\scan.l"
{ return INSTR; } // also FIND and other variations
	YY_BREAK
/* aliases for MID found in some versions */
case 93:
YY_RULE_SETUP
#line 159 ".\\scan.l"
{ return MID; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 160 ".\\scan.l"
{ return MID; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 161 ".\\scan.l"
{ return MID; }
	YY_BREAK
/* aliases for MID found in some versions */
case 96:
YY_RULE_SETUP
#line 163 ".\\scan.l"
{ return INKEY; }
	YY_BREAK
/* system functions */
case 97:
YY_RULE_SETUP
#line 166 ".\\scan.l"
{ return ADR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 167 ".\\scan.l"
{ return FRE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 168 ".\\scan.l"
{ return TAB; }   // also a statement in Integer BASIC
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 169 ".\\scan.l"
{ return SPC; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 170 ".\\scan.l"
{ return SPC; }   // from HP, same as SPC
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 171 ".\\scan.l"
{ return PEEK; }  // also EXAM (North Star) and FETCH (Digital Group Opus)
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 172 ".\\scan.l"
{ return POS; }   // COUNT in Atom
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 173 ".\\scan.l"
{ return USR; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 174 ".\\scan.l"
{ return LIN; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 175 ".\\scan.l"
{ return EL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 176 ".\\scan.l"
{ return ER; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 177 ".\\scan.l"
{ return ERR; }
	YY_BREAK
/* various operators and punctuation */
case 109:
YY_RULE_SETUP
#line 180 ".\\scan.l"
{ return yytext[0]; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 181 ".\\scan.l"
{ return MOD; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 182 ".\\scan.l"
{ return DIV; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 183 ".\\scan.l"
{ return MAX; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 184 ".\\scan.l"
{ return MIN; }
	YY_BREAK
/* alternate form for power */
case 114:
YY_RULE_SETUP
#line 187 ".\\scan.l"
{ return '^'; } // FIXME: we should have a separate token for this?
	YY_BREAK
/* binary operators */
case 115:
YY_RULE_SETUP
#line 190 ".\\scan.l"
{ return AND; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 191 ".\\scan.l"
{ return OR; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 192 ".\\scan.l"
{ return NOT; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 193 ".\\scan.l"
{ return XOR; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 194 ".\\scan.l"
{ return EQV; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 195 ".\\scan.l"
{ return IMP; }
	YY_BREAK
/* comparison operators */
case 121:
YY_RULE_SETUP
#line 198 ".\\scan.l"
{ return CMP_LE; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 199 ".\\scan.l"
{ return CMP_LE; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 200 ".\\scan.l"
{ return CMP_GE; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 201 ".\\scan.l"
{ return CMP_GE; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 202 ".\\scan.l"
{ return CMP_NE; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 203 ".\\scan.l"
{ return CMP_NE; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 204 ".\\scan.l"
{ return CMP_HASH; } // use a separate token here to preserve it in LIST
	YY_BREAK
/* defs added in Extended BASIC */
/* FIXME: these are actually easy to do, simply run them as DIMs so they get entered into the var list */
case 128:
YY_RULE_SETUP
#line 208 ".\\scan.l"
{ return DEFSTR; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 209 ".\\scan.l"
{ return DEFINT; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 210 ".\\scan.l"
{ return DEFSNG; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 211 ".\\scan.l"
{ return DEFDBL; }
	YY_BREAK
/* other string commands and functions */
case 132:
YY_RULE_SETUP
#line 214 ".\\scan.l"
{ return CHANGE; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 215 ".\\scan.l"
{ return CONVERT; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 216 ".\\scan.l"
{ return UCASE; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 217 ".\\scan.l"
{ return LCASE; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 218 ".\\scan.l"
{ return SPC; }   // returns n spaces as a value, which is how our SPC works anyway
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 219 ".\\scan.l"
{ return STRNG; } // returns n copies of a given string
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 220 ".\\scan.l"
{ return STRNG; } // alternate form of STRING
	YY_BREAK
/* commodore-style TIME and TIME$ */
case 139:
YY_RULE_SETUP
#line 223 ".\\scan.l"
{ return TIME_STR; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 224 ".\\scan.l"
{ return TIME; }
	YY_BREAK
/* and their alternate short forms */
case 141:
YY_RULE_SETUP
#line 226 ".\\scan.l"
{ return TIME_STR; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 227 ".\\scan.l"
{ return TIME; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 228 ".\\scan.l"
{ return TIME_STR; } // from BASIC-PLUS, Univac System 9 has CLK(x) where x is numeric
	YY_BREAK
/* HEX, OCT and BIN conversions */
case 144:
YY_RULE_SETUP
#line 231 ".\\scan.l"
{ return BIN; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 232 ".\\scan.l"
{ return BINSTR; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 233 ".\\scan.l"
{ return HEX; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 234 ".\\scan.l"
{ return HEXSTR; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 235 ".\\scan.l"
{ return OCT; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 236 ".\\scan.l"
{ return OCTSTR; }
	YY_BREAK
/* array utilities */
case 150:
YY_RULE_SETUP
#line 239 ".\\scan.l"
{ return UBOUND; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 240 ".\\scan.l"
{ return LBOUND; }
	YY_BREAK
/* line labels, procedures, etc. */
case 152:
YY_RULE_SETUP
#line 243 ".\\scan.l"
{ return LABEL; }
	YY_BREAK
/* matrix commands and functions */
case 153:
YY_RULE_SETUP
#line 246 ".\\scan.l"
{ return MAT; }     // assignments
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 247 ".\\scan.l"
{ return MATZER; }  // zero matrix
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 248 ".\\scan.l"
{ return MATCON; }  // all-1 matrix
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 249 ".\\scan.l"
{ return MATIDN; }  // identity matrix
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 250 ".\\scan.l"
{ return MATINV; }  // invert
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 251 ".\\scan.l"
{ return MATTRN; }  // transpose
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 252 ".\\scan.l"
{ return MATDET; }  // determinant
	YY_BREAK
/* hex, oct and bin strings encoding numbers */
case 160:
YY_RULE_SETUP
#line 255 ".\\scan.l"
{
            yylval.d = (double)strtol(yytext + 1, NULL, 16);
            return NUMBER;
          }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 259 ".\\scan.l"
{
            yylval.d = (double)strtol(yytext + 2, NULL, 16);
            return NUMBER;
          }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 263 ".\\scan.l"
{
            yylval.d = (double)strtol(yytext + 2, NULL, 8);
            return NUMBER;
          }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 267 ".\\scan.l"
{
            yylval.d = (double)strtol(yytext + 2, NULL, 2);
            return NUMBER;
          }
	YY_BREAK
/* other numeric constants and line numbers */
case 164:
YY_RULE_SETUP
#line 273 ".\\scan.l"
{
            yylval.d = strtod(yytext, NULL);
            return NUMBER;
          }
	YY_BREAK
/* user defined functions */
case 165:
YY_RULE_SETUP
#line 279 ".\\scan.l"
{
            yylval.s = str_new(yytext);
            return FUNCTION_NAME;
          }
	YY_BREAK
/* variable references */
/* currently set to allow only one or two chars plus an optional type indicator
    replace the ? with a * for multi-char variables */
case 166:
YY_RULE_SETUP
#line 287 ".\\scan.l"
{
            yylval.s = str_new(yytext);
            return VARIABLE_NAME;
          }
	YY_BREAK
/* string constants */
case 167:
YY_RULE_SETUP
#line 293 ".\\scan.l"
{
            yytext[strlen(yytext) - 1] = '\0';
            yylval.s = str_new(yytext + 1);
            return STRING;
          }
	YY_BREAK
/* preserve line ends */
case 168:
YY_RULE_SETUP
#line 300 ".\\scan.l"
{ BEGIN(INITIAL); return '\n'; }
	YY_BREAK
/* eat other whitespace */
case 169:
YY_RULE_SETUP
#line 303 ".\\scan.l"
{  }
	YY_BREAK
/* DATA statements convert everything to a string */

case 170:
YY_RULE_SETUP
#line 307 ".\\scan.l"
{
            // eat any leading and trailing whitespace
            yytext = str_trim(yytext);
            
            // and quotes
            yytext = str_unquote(yytext);

            yylval.s = str_new(yytext);
            return STRING;
          }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 318 ".\\scan.l"
{ return ','; } // triggers the exprlist syntax
	YY_BREAK
/* colons or line-ends end the data statement and reset the state */
case 172:
YY_RULE_SETUP
#line 321 ".\\scan.l"
{ BEGIN(INITIAL); return ':'; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 322 ".\\scan.l"
{ BEGIN(INITIAL); return '\n'; }
	YY_BREAK

case 174:
YY_RULE_SETUP
#line 325 ".\\scan.l"
printf("Bad input character '%s' at line %d\n", yytext, yylineno);
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 327 ".\\scan.l"
ECHO;
	YY_BREAK
#line 2048 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 430 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 430 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 429);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 327 ".\\scan.l"

